### ISSUE TITLE
avoid panic!()

### ISSUE THREAD

**Issue by mustakimur** [DamoSWL/8000_shell_rust#1]
There is a panic!() for following input:
```rust
mustakim@localhost:/csci-shell/home$ pwd
/csci-shell/home
mustakim@localhost:/csci-shell/home$ ls
text.txt
log.txt
hello
mustakim@localhost:/csci-shell/home$ history
pwd
ls
history
mustakim@localhost:/csci-shell/home$ pwd
|s -l
find . -name text.txt
cd hello
ls -l | pwd
history
exit/csci-shell/home
mustakim@localhost:/csci-shell/home$ No such file or directory (os error 2)
mustakim@localhost:/csci-shell/home$ /csci-shell/home/text.txt
mustakim@localhost:/csci-shell/home$ mustakim@localhost:/csci-shell/home/hello$ /csci-shell/home/hello
mustakim@localhost:/csci-shell/home/hello$ pwd
ls
history
pwd
|s -l
find . -name text.txt
cd hello
ls -l | pwd
history
mustakim@localhost:/csci-shell/home/hello$ exit
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:286:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by DamoSWL** [comment]
I have solved this problem in v1.0

**Comment by DamoSWL** [comment]
> There is a panic!() for following input:
> 
> ```rust
> mustakim@localhost:/csci-shell/home$ pwd
> /csci-shell/home
> mustakim@localhost:/csci-shell/home$ ls
> text.txt
> log.txt
> hello
> mustakim@localhost:/csci-shell/home$ history
> pwd
> ls
> history
> mustakim@localhost:/csci-shell/home$ pwd
> |s -l
> find . -name text.txt
> cd hello
> ls -l | pwd
> history
> exit/csci-shell/home
> mustakim@localhost:/csci-shell/home$ No such file or directory (os error 2)
> mustakim@localhost:/csci-shell/home$ /csci-shell/home/text.txt
> mustakim@localhost:/csci-shell/home$ mustakim@localhost:/csci-shell/home/hello$ /csci-shell/home/hello
> mustakim@localhost:/csci-shell/home/hello$ pwd
> ls
> history
> pwd
> |s -l
> find . -name text.txt
> cd hello
> ls -l | pwd
> history
> mustakim@localhost:/csci-shell/home/hello$ exit
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:286:30
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

I have solved this problem in v1.0

**Comment by mustakimur** [comment]
if so, you can close the issue.

**Comment by DamoSWL** [comment]
solved
