### ISSUE TITLE
write error handler with meaningful statements

### ISSUE THREAD

**Issue by mustakimur** [DamoSWL/8000_shell_rust#2]
For the following input:
```
mustakim@localhost:/csci-shell/home$ pwd
/csci-shell/home
mustakim@localhost:/csci-shell/home$ |s -l
No such file or directory (os error 2)
mustakim@localhost:/csci-shell/home$ cd hello    
mustakim@localhost:/csci-shell/home/hello$ ls -l | pwd
/csci-shell/home/hello
```
1. No such file or directory (os error 2)
What does that mean?
2. ls -l | pwd output is not matched with project 1.

**Comment by DamoSWL** [comment]
For the first question, there is something wrong in my code and I have solved it in v1.0
For the second question, I have checked both the first project and this project, the output for that command is correct in this project, while there is some minor problem in the first project

**Comment by DamoSWL** [comment]
> For the following input:
> 
> ```
> mustakim@localhost:/csci-shell/home$ pwd
> /csci-shell/home
> mustakim@localhost:/csci-shell/home$ |s -l
> No such file or directory (os error 2)
> mustakim@localhost:/csci-shell/home$ cd hello    
> mustakim@localhost:/csci-shell/home/hello$ ls -l | pwd
> /csci-shell/home/hello
> ```
> 
> 1. No such file or directory (os error 2)
>    What does that mean?
> 2. ls -l | pwd output is not matched with project 1.

For the first question, there is something wrong in my code and I have solved it in v1.0
For the second question, I have checked both the first project and this project, the output for that command is correct in this project, while there is some minor problem in the first project

**Comment by mustakimur** [comment]
if so, you can close the issue.

**Comment by DamoSWL** [comment]
solved
